version: '2'
services:
  composer:
    image: prooph/composer:8.2
    volumes:
      - .:/app
    links:
      - postgres:postgres
      - mariadb:mariadb
      - mysql:mysql
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1

  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=event_store_tests
      - POSTGRES_HOST_AUTH_METHOD=trust

  mariadb:
    image: mariadb:10.11.2
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=event_store_tests

  mysql:
    image: mysql:8.0.32
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=event_store_tests


# dckr_pat_fIg5nLqNSSec5mIXu2uCWeLQf04